// <auto-generated />
using AppointmentScheduler.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using MySql.Data.EntityFrameworkCore.Storage.Internal;
using System;

namespace AppointmentScheduler.Migrations
{
    [DbContext(typeof(AppointmentSchedulerContext))]
    [Migration("20180301192459_Initial Professor Model")]
    partial class InitialProfessorModel
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("AppointmentScheduler.Entities.Professor", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Active");

                    b.Property<bool>("Admin");

                    b.Property<string>("Email");

                    b.Property<string>("Name");

                    b.Property<string>("Password");

                    b.Property<string>("RoomNumber");

                    b.Property<string>("Title");

                    b.HasKey("ID");

                    b.ToTable("Professors");
                });
#pragma warning restore 612, 618
        }
    }
}
